// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCthsXex4XAG82GnaSC76EMlZQSXUs0YuU',
    appId: '1:464478048893:web:ebaca36ec9e09c49725714',
    messagingSenderId: '464478048893',
    projectId: 'capstone-project-jjw8584',
    authDomain: 'capstone-project-jjw8584.firebaseapp.com',
    storageBucket: 'capstone-project-jjw8584.firebasestorage.app',
    measurementId: 'G-BW6X63E8H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6xw5v3pZQMCj1YDCZg0x6fYDQZtOAUrE',
    appId: '1:464478048893:android:6ba51fa8f13a2ec4725714',
    messagingSenderId: '464478048893',
    projectId: 'capstone-project-jjw8584',
    storageBucket: 'capstone-project-jjw8584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdiDrA8DZASKiNaXVEkMtoP9WqPiwOktI',
    appId: '1:464478048893:ios:26fc184b3f36d57f725714',
    messagingSenderId: '464478048893',
    projectId: 'capstone-project-jjw8584',
    storageBucket: 'capstone-project-jjw8584.firebasestorage.app',
    iosBundleId: 'com.example.safetyandmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdiDrA8DZASKiNaXVEkMtoP9WqPiwOktI',
    appId: '1:464478048893:ios:26fc184b3f36d57f725714',
    messagingSenderId: '464478048893',
    projectId: 'capstone-project-jjw8584',
    storageBucket: 'capstone-project-jjw8584.firebasestorage.app',
    iosBundleId: 'com.example.safetyandmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCthsXex4XAG82GnaSC76EMlZQSXUs0YuU',
    appId: '1:464478048893:web:0424b84e4a6a6a4b725714',
    messagingSenderId: '464478048893',
    projectId: 'capstone-project-jjw8584',
    authDomain: 'capstone-project-jjw8584.firebaseapp.com',
    storageBucket: 'capstone-project-jjw8584.firebasestorage.app',
    measurementId: 'G-J9VXPJV4Z2',
  );

}